# Generated by Django 2.0.1 on 2018-01-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamientos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateField()),
                ('presentada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_del_paciente', models.TextField()),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('medicacion', models.TextField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Historia')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.ObraSocial')),
            ],
        ),
        migrations.CreateModel(
            name='SesionTerapeutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discurso', models.TextField()),
                ('fecha_sesion', models.DateField()),
                ('facturada', models.BooleanField()),
                ('numero_sesion', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.ObraSocial'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Paciente'),
        ),
    ]
