# Generated by Django 2.0.1 on 2018-03-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamientos', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Anamnesis',
            },
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateField()),
                ('presentada', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Autorizaciones',
                'ordering': ['fecha_autorizacion'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_del_paciente', models.TextField()),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('medicacion', models.TextField()),
                ('diagnostico', models.TextField()),
                ('inicio_tratamiento', models.DateField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Historia')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.ObraSocial')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='SesionTerapeutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discurso', models.TextField()),
                ('fecha_sesion', models.DateField()),
                ('facturada', models.BooleanField()),
                ('numero_sesion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Sesiones Terapeuticas',
                'ordering': ['fecha_sesion'],
            },
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.ObraSocial'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Paciente'),
        ),
    ]
