# Generated by Django 2.0.1 on 2018-03-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psicologia.Profesional'),
        ),
    ]
