# Generated by Django 2.0.1 on 2018-01-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnesis',
            options={'verbose_name_plural': 'Anamnesis'},
        ),
        migrations.AlterModelOptions(
            name='autorizacion',
            options={'ordering': ['fecha_autorizacion'], 'verbose_name_plural': 'Autorizaciones'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido'], 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='sesionterapeutica',
            options={'ordering': ['fecha_sesion'], 'verbose_name_plural': 'Sesiones Terapeuticas'},
        ),
    ]
